// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzDH0Gl3-A09HgzD9Q_Sbg_3Rl8hw-DD8',
    appId: '1:411225006646:web:7ab7e627ecc19ca436ae97',
    messagingSenderId: '411225006646',
    projectId: 'cs21-22706',
    authDomain: 'cs21-22706.firebaseapp.com',
    storageBucket: 'cs21-22706.appspot.com',
    measurementId: 'G-B4L9HMZCHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnb3HCQsk2O89MD5i47Co16suo9q7v0TA',
    appId: '1:411225006646:android:a9924d198e82161536ae97',
    messagingSenderId: '411225006646',
    projectId: 'cs21-22706',
    storageBucket: 'cs21-22706.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARAgK_cbE2zaX1QoUAh4KjcP46rRFXdVk',
    appId: '1:411225006646:ios:1c98029de486d33d36ae97',
    messagingSenderId: '411225006646',
    projectId: 'cs21-22706',
    storageBucket: 'cs21-22706.appspot.com',
    iosClientId: '411225006646-dmhlibel6ofpdp72ks04fvfr49gjgmcu.apps.googleusercontent.com',
    iosBundleId: 'com.example.birthdayreminde',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARAgK_cbE2zaX1QoUAh4KjcP46rRFXdVk',
    appId: '1:411225006646:ios:1c98029de486d33d36ae97',
    messagingSenderId: '411225006646',
    projectId: 'cs21-22706',
    storageBucket: 'cs21-22706.appspot.com',
    iosClientId: '411225006646-dmhlibel6ofpdp72ks04fvfr49gjgmcu.apps.googleusercontent.com',
    iosBundleId: 'com.example.birthdayreminde',
  );
}
